// Syncthing Monitor - Constants

// Timeout values (milliseconds)
const DEVICE_ID_REQUEST_TIMEOUT_MS = 5000;
const MONITOR_INTERVAL_MS = 30 * 1000; // 30 seconds
const OPERATION_DELAY_MS = 500;
const ERROR_RETRY_DELAY_MS = 5 * 1000; // 5 seconds

// Syncthing configuration
const SYNCTHING_RESCAN_INTERVAL_SECONDS = 900; // 15 minutes
const SYNCTHING_MAX_CONFLICTS = 0;

// Sync monitoring
const MAX_SYNC_WAIT_EXECUTIONS = 60; // ~30 minutes at 30s intervals
const CLOCK_SKEW_TOLERANCE_MS = 5000; // 5 seconds tolerance for timestamp comparison
const LEADER_ELECTION_MIN_EXECUTIONS = 2;
const LEADER_ELECTION_EXECUTIONS_PER_INDEX = 10;

// Sync completion thresholds
const SYNC_COMPLETE_PERCENTAGE = 100;

module.exports = {
  DEVICE_ID_REQUEST_TIMEOUT_MS,
  MONITOR_INTERVAL_MS,
  OPERATION_DELAY_MS,
  ERROR_RETRY_DELAY_MS,
  SYNCTHING_RESCAN_INTERVAL_SECONDS,
  SYNCTHING_MAX_CONFLICTS,
  MAX_SYNC_WAIT_EXECUTIONS,
  CLOCK_SKEW_TOLERANCE_MS,
  LEADER_ELECTION_MIN_EXECUTIONS,
  LEADER_ELECTION_EXECUTIONS_PER_INDEX,
  SYNC_COMPLETE_PERCENTAGE,
};
